name: build app
on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install yarn
        run: npm install yarn

      - name: install dipendence
        run: yarn install

      - name: run build
        run: yarn install