name: print from file
on: push

jobs: 
  print:
    runs-on: ubuntu-latest
    step:
    - name: checkout repository
      uses: actions/checkout@v3


    - name: print hello-world on terminal
      run: echo "$(cat hello_world.txt)"