name: print from file
on: push

jobs: 
  print:
    runs-on: ubuntu-latest
    step:
      - name: checkout repository
        run: actions/checkout@v3


      - name: print hello-world on terminal
        run: echo 's(cat hello_world.txt)'